/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import br.com.lpoo.projetolpooe1_luana.dao.PersistenciaJPA;
import br.com.lpoo.projetolpooe1_luana.model.Departamentos;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author luana
 */
public class TelaDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form TelaFuncionario
     */
     private PersistenciaJPA jpa;
    public TelaDepartamento() {
        initComponents();
         jpa = new PersistenciaJPA();
        listarDepartamentos();
    }
    
    private void listarDepartamentos() {
    JLDepartamento.clearSelection();
    jpa.conexaoAberta();
    List<Departamentos> dep = jpa.getDepartamentos();
    DefaultListModel<Departamentos> mod = new DefaultListModel<>();
    for (Departamentos d : dep) {
        mod.addElement(d);
    }
    JLDepartamento.setModel(mod);
    jpa.fecharConexao();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JLDepartamento = new javax.swing.JList<>();
        BTAdicionar = new javax.swing.JButton();
        BTEditar = new javax.swing.JButton();
        BTRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de funcionarios");

        jLabel1.setText("Departamentos");

        jScrollPane1.setViewportView(JLDepartamento);

        BTAdicionar.setText("Adicionar");
        BTAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTAdicionarActionPerformed(evt);
            }
        });

        BTEditar.setText("Editar");
        BTEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEditarActionPerformed(evt);
            }
        });

        BTRemover.setText("Remover");
        BTRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTAdicionar)
                                .addGap(47, 47, 47)
                                .addComponent(BTEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTAdicionar)
                    .addComponent(BTEditar)
                    .addComponent(BTRemover))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEditarActionPerformed
        Departamentos dpSelecionado
                = JLDepartamento.getSelectedValue();
        if (dpSelecionado != null) {
            
            TelaOficial telaCadastro = new TelaOficial(this, true);

            telaCadastro.setDepartamento(dpSelecionado);
            

            telaCadastro.setVisible(true);

            listarDepartamentos();

        }
    }//GEN-LAST:event_BTEditarActionPerformed

    private void BTAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTAdicionarActionPerformed
       TelaOficial telaof = new TelaOficial(this, rootPaneCheckingEnabled);

        telaof.setVisible(true);

        listarDepartamentos();
        
    }//GEN-LAST:event_BTAdicionarActionPerformed

    private void BTRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTRemoverActionPerformed
          Departamentos departamentoSelecionado = JLDepartamento.getSelectedValue();
        if (departamentoSelecionado != null) {
            int confirmacaoDel = JOptionPane.showConfirmDialog(rootPane,
                    "Tem certeza que deseja remover o departamento " + departamentoSelecionado.getNome());
            if (confirmacaoDel == JOptionPane.YES_OPTION) {
                try {

                    jpa.conexaoAberta();
                    jpa.remover(departamentoSelecionado);
                   jpa.fecharConexao();
                    listarDepartamentos();

                } catch (Exception e) {
                    System.err.println("Erro ao excluir funcionario: " + e.getMessage());
                } finally {
                    jpa.fecharConexao();
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Nenhum departamento selecionado");
        }
    }//GEN-LAST:event_BTRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTAdicionar;
    private javax.swing.JButton BTEditar;
    private javax.swing.JButton BTRemover;
    private javax.swing.JList<Departamentos> JLDepartamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
