/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import br.com.lpoo.projetolpooe1_luana.dao.PersistenciaJPA;
import br.com.lpoo.projetolpooe1_luana.model.Departamentos;
import br.com.lpoo.projetolpooe1_luana.model.Diretores;
import br.com.lpoo.projetolpooe1_luana.model.Empresa;
import br.com.lpoo.projetolpooe1_luana.model.Funcionarios;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author luana
 */
public class TelaOficial extends javax.swing.JDialog {

    /**
     * Creates new form TelaOficial
     */
    private Departamentos departamento;
    private PersistenciaJPA jpa;

    public TelaOficial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        jpa = new PersistenciaJPA();
        listarFuncionarios();
        listarEmpresa();
        listarDiretores();
    }

    private void listarFuncionarios() {
        BoxFuncionario.removeAll();

        jpa.conexaoAberta();
        List<Funcionarios> list = jpa.getFuncionarios();
        for (Funcionarios f : list) {
            BoxFuncionario.addItem(f);
        }

        jpa.fecharConexao();
    }

    private void listarDiretores() {
        BoxDiretor.removeAll();

        jpa.conexaoAberta();
        List<Diretores> list = jpa.getDiretores();
        for (Diretores f : list) {
            BoxDiretor.addItem(f);
        }

        jpa.fecharConexao();
    }

    private void listarEmpresa() {
        BoxEmpresa.removeAll();

        jpa.conexaoAberta();
        List<Empresa> list = jpa.getEmpresa();
        for (Empresa f : list) {
            BoxEmpresa.addItem(f);
        }

        jpa.fecharConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLNome = new javax.swing.JLabel();
        TXTNome = new javax.swing.JTextField();
        JLLocal = new javax.swing.JLabel();
        TXTLocal = new javax.swing.JTextField();
        JLTelefone = new javax.swing.JLabel();
        TXTTelefone = new javax.swing.JTextField();
        JLEmpresa = new javax.swing.JLabel();
        BoxEmpresa = new javax.swing.JComboBox<>();
        JLDiretor = new javax.swing.JLabel();
        BoxDiretor = new javax.swing.JComboBox<>();
        JLFuncionario = new javax.swing.JLabel();
        BoxFuncionario = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        BTCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicione ou edite um departamento");

        JLNome.setText("Nome:");

        TXTNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNomeActionPerformed(evt);
            }
        });

        JLLocal.setText("Local:");

        TXTLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTLocalActionPerformed(evt);
            }
        });

        JLTelefone.setText("Telefone:");

        TXTTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTelefoneActionPerformed(evt);
            }
        });

        JLEmpresa.setText("Empresa: ");

        JLDiretor.setText("Diretor:");

        JLFuncionario.setText("Funcionario:");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BTCancelar.setText("Cancelar");
        BTCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLNome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BoxDiretor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TXTTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(BoxEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BoxFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TXTNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TXTLocal, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(BTCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNome)
                    .addComponent(TXTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLLocal)
                    .addComponent(TXTLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLTelefone)
                    .addComponent(TXTTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLEmpresa)
                    .addComponent(BoxEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLDiretor)
                    .addComponent(BoxDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLFuncionario)
                    .addComponent(BoxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(BTCancelar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNomeActionPerformed

    private void TXTLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTLocalActionPerformed

    private void TXTTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTelefoneActionPerformed

    private void BTCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Verifica se o departamento é nulo para saber se é uma nova inserção ou uma edição
        if (departamento == null) {
            departamento = new Departamentos();
        }

// Coleta os dados dos campos
        String nome = TXTNome.getText().trim();
        String local = TXTLocal.getText().trim();
        String telefone = TXTTelefone.getText().trim();
        Empresa empresa = (Empresa) BoxEmpresa.getSelectedItem();
        Diretores diretor = (Diretores) BoxDiretor.getSelectedItem();
        Funcionarios funcionario = (Funcionarios) BoxFuncionario.getSelectedItem();

// Valida se os campos obrigatórios foram preenchidos
        if (nome.isEmpty() || local.isEmpty() || telefone.isEmpty() || empresa == null) {
            JOptionPane.showMessageDialog(rootPane, "Todos os campos obrigatórios devem ser preenchidos.");
            return; // Interrompe a execução do método
        }

// Configura os dados do departamento
        departamento.setNome(nome);
        departamento.setLocal(local);
        departamento.setTelefone(telefone);
        departamento.setEmpresa(empresa);
        departamento.setDiretores(diretor);
        departamento.setFuncionarios(funcionario);

        try {
            jpa = new PersistenciaJPA();
            jpa.conexaoAberta();

            if (departamento.getId() == null) {
                // Novo departamento, persiste como novo
                jpa.persist(departamento);
                JOptionPane.showMessageDialog(rootPane, "Departamento adicionado com sucesso.");
            } else {
                // Atualização do departamento existente
                Departamentos depEdit = (Departamentos) jpa.find(Departamentos.class, departamento.getId());
                if (depEdit != null) {
                    depEdit.setNome(nome);
                    depEdit.setLocal(local);
                    depEdit.setTelefone(telefone);
                    depEdit.setEmpresa(empresa);
                    depEdit.setDiretores(diretor);
                    depEdit.setFuncionarios(funcionario);

                    jpa.persist(depEdit);
                    JOptionPane.showMessageDialog(rootPane, "Departamento atualizado com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Departamento não encontrado.");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao processar departamento: " + e.getMessage());
        } finally {
            if (jpa != null) {
                jpa.fecharConexao();
            }
        }

// Fecha a janela
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOficial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOficial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOficial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOficial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaOficial dialog = new TelaOficial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public Departamentos getDepartamento() {
        return departamento;
    }

    public void setDepartamento(Departamentos departamento) {
        this.departamento = departamento;
        TXTNome.setText(departamento.getNome());
        TXTLocal.setText(departamento.getLocal());
        TXTTelefone.setText(departamento.getTelefone());
        BoxEmpresa.setSelectedItem((Empresa) departamento.getEmpresa());
        BoxDiretor.setSelectedItem((Diretores) departamento.getDiretores());
        BoxFuncionario.setSelectedItem((Funcionarios) departamento.getFuncionarios());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTCancelar;
    private javax.swing.JComboBox<Diretores> BoxDiretor;
    private javax.swing.JComboBox<Empresa> BoxEmpresa;
    private javax.swing.JComboBox<Funcionarios> BoxFuncionario;
    private javax.swing.JLabel JLDiretor;
    private javax.swing.JLabel JLEmpresa;
    private javax.swing.JLabel JLFuncionario;
    private javax.swing.JLabel JLLocal;
    private javax.swing.JLabel JLNome;
    private javax.swing.JLabel JLTelefone;
    private javax.swing.JTextField TXTLocal;
    private javax.swing.JTextField TXTNome;
    private javax.swing.JTextField TXTTelefone;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
